*[main][~/projects/valentineportfolio]$ cd portfolio                                                                                                                                                                                   rvm:
*[main][~/projects/valentineportfolio/portfolio]$ ls                                                                                                                                                                                   rvm:
asgi.py  __init__.py  __pycache__  settings.py  urls.py  wsgi.py
*[main][~/projects/valentineportfolio/portfolio]$ ls                                                                                                                                                                                   rvm:
asgi.py  __init__.py  __pycache__  settings.py  urls.py  wsgi.py
*[main][~/projects/valentineportfolio/portfolio]$ touch secret.py                                                                                                                                                                      rvm:
*[main][~/projects/valentineportfolio/portfolio]$ python3 manage.py shell                                                                                                                                                              rvm:
python3: can't open file '/home/professor/projects/valentineportfolio/portfolio/manage.py': [Errno 2] No such file or directory
*[main][~/projects/valentineportfolio/portfolio]$ cd ..                                                                                                                                                                                rvm:
*[main][~/projects/valentineportfolio]$ python3 manage.py shell                                                                                                                                                                        rvm:
Python 3.9.9 (main, Nov 20 2021, 21:30:06)
[GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from .models import VisualArt
Traceback (most recent call last):
  File "<console>", line 1, in <module>
KeyError: "'__name__' not in globals"
>>> from posts.models import VisualArt
>>> obj = VisualArt.objects.get(id=1)
>>> obj
<VisualArt: Art: Discord Something>
>>> obj.image_url
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'VisualArt' object has no attribute 'image_url'
>>> obj.art.path
'/home/professor/projects/valentineportfolio/art/271744769_1399444367177299_6437739369177991725_n.png'
>>> exit()
*[main][~/projects/valentineportfolio]$ python3 manage.py runserver 0.0.0.0:8080                                                                                                                                                       rvm:
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
February 04, 2022 - 15:52:07
Django version 4.0.2, using settings 'portfolio.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Error: That port is already in use.
*[main][~/projects/valentineportfolio]$                                                                                                                                                                                                rvm:













